version: '2'
services:
  daarbibli-app:
    image: daarbibli
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://daarbibli-postgresql:5432/DaarBibli
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  daarbibli-postgresql:
    extends:
      file: postgresql.yml
      service: daarbibli-postgresql
